name: Generate Sitemap

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  sitemap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Generate sitemap
        run: |
          echo '<?xml version="1.0" encoding="UTF-8"?>' > sitemap.xml
          echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' >> sitemap.xml

          BASE_URL="https://remanentejehova3311.github.io/RemanenteJehova"

          echo "<url><loc>$BASE_URL/</loc></url>" >> sitemap.xml

          for file in $(find . -name "*.html" \
            -not -path "./.git/*" \
            -not -path "./partials/*" \
            -not -name "google*.html"); do
            
            url=$(echo $file | sed 's|^\./||')

            echo "<url><loc>$BASE_URL/$url</loc></url>" >> sitemap.xml
          done

          echo '</urlset>' >> sitemap.xml

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "auto update sitemap"
          branch: sitemap-update
          title: "Auto update sitemap"
          body: "Automatically generated sitemap update"
